### ISSUE TITLE
Documentation with screenshots

### ISSUE THREAD

**Issue by Benji377** [tfobz/carbon-calculator#36]
**Is your feature request related to a problem? Please describe.**
When looking at code and its structure, it might look clear and logical to someone that worked on it, but when you first look at it, you might be very confused. The general difficulty is in finding each component in HTML. For example, if you see something on the page that you would like to edit, it's quite hard to find the component producing that page in the project. This happens because the component names are unclear

**Describe the solution you'd like**
To solve this issue, it might be a good idea to create a markdown file that gets included in the Compodoc documentation, containing a small screenshot of each component and a description for it.

**Describe alternatives you've considered**
Instead of screenshot, just add the description of the different modules and their path

**Comment by mwallnoefer** [comment]
Hi @Chris3444,

how far have we gone in respect to the docs? Since I would need to start the final assessment, since the school term is slowly coming to the end. Also talked to @Benji377 today.
