### ISSUE TITLE
App with PWA support

### ISSUE THREAD

**Issue by Benji377** [tfobz/carbon-calculator#37]
**Is your feature request related to a problem? Please describe.**
PWA stands for Progressive Web App, and it essentially creates an app from a website. Angular offers this as a feature and might be a cool and simple addition to the project. 

**Describe the solution you'd like**
A possible solution might be [following this tutorial](https://angular.io/guide/service-worker-getting-started)

**Comment by hannest03** [comment]
PWA support was already added with 982a078879105a21ad3de2156de142f80f271653

**Comment by Benji377** [comment]
True, sorry I forgot that
