### ISSUE TITLE
rest to previous commit

### ISSUE THREAD

**Issue by Chris3444** [tfobz/carbon-calculator#81]
need to reset to commit a7dd1aa01427ee38133678024f6de3b3bf0ad854 
The command is:  git reset --hard a7dd1aa01427ee38133678024f6de3b3bf0ad854
Then to push this change the command is: git push origin HEAD --force

**Comment by mwallnoefer** [comment]
@Chris3444 the GitHub hooks blocked the force push of the resetted branch, so I decided to create and push a revert commit 91fce7d3aee54751fd46480aa4402d6b599ca56e. I guess that it should be ok now.
